### ISSUE TITLE
Reference packages to import

### ISSUE THREAD

**Issue by wst24365888** [bytecodealliance/ComponentizeJS#107]
First of all, thanks for this awesome project.

I'm wondering if I can [reference packages to import like `cargo component`](https://component-model.bytecodealliance.org/language-support/rust.html#referencing-the-package-to-import) for `ComponentizeJS` (and also for `componentize-py` but not tested yet).

The project structure looks like this. The wit package `foo` is implemented in another project, and I will combine the implementation component with this component together using `wasm-tools` later.

```
$ tree -I node_modules
.
├── package.json
├── pnpm-lock.yaml
├── source.js
└── wit
    ├── cli/
    ├── clocks/
    ├── filesystem/
    ├── foo
    │   ├── bar.wit
    │   └── world.wit
    ├── http/
    ├── io/
    ├── random/
    ├── sockets/
    └── world.wit
```

But it seems that I can't use `jco` and `ComponentizeJS` to accomplish this task..

```
(jco componentize) ComponentError: package not found
     --> //?/C:/Users/<USER_NAME>/Desktop/componentized-js-test/wit/world.wit:4:10
      |
    4 |   import wasi:foo/bar@0.1.0;
      |          ^-------
    at spliceBindings (file:///C:/Users/<USER_NAME>/AppData/Local/pnpm/global/5/.pnpm/@bytecodealliance+componentize-js@0.8.3/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:3800:11)
    at componentize (file:///C:/Users/<USER_NAME>/AppData/Local/pnpm/global/5/.pnpm/@bytecodealliance+componentize-js@0.8.3/node_modules/@bytecodealliance/componentize-js/src/componentize.js:50:64)
    at async componentize (file:///C:/Users/<USER_NAME>/AppData/Local/pnpm/global/5/.pnpm/@bytecodealliance+jco@1.2.4/node_modules/@bytecodealliance/jco/src/cmd/componentize.js:15:25)
    at async file:///C:/Users/<USER_NAME>/AppData/Local/pnpm/global/5/.pnpm/@bytecodealliance+jco@1.2.4/node_modules/@bytecodealliance/jco/src/jco.js:186:9
```

To reproduce, please head over to [this repo](https://github.com/wst24365888/componentize-test).

**Comment by guybedford** [comment]
You need to restructure your WIT folder to contain a `deps` subfolder. Something like:

```
cd wit
mkdir deps
mv * deps/
mv deps/world.wit .
```

**Comment by cdata** [comment]
I was clued in to "deps" when I stumbled upon the `wit-deps` repo. This issue is the sole place I've been able to find a pointer about how to use them. Is there a canonical place to go to read more about how deps are supposed to be resolved?

**Comment by vados-cosmonic** [comment]
*very* late here, but the best canonical place to learn about how to pull deps is the Component Model Book! In this case the [section on distribution](https://component-model.bytecodealliance.org/composing-and-distributing/distributing.html).

`wit-deps` isn't the tool to use any more (we now have `wkg`), but closing this issue out as the problem was solved long ago, and documentation is *dramatically* better today (though still not perfect!)
