### ISSUE TITLE
Resource function names should be kebab-cased

### ISSUE THREAD

**Issue by cataggar** [bytecodealliance/ComponentizeJS#145]
I've been trying to make my first resource definition. I keep getting an error message that my `compilerOptions` resource function is not valid.

```
$ bunx jco componentize cowsay.js --wit src/cowsay.wit -o cowsay.wasm
(jco componentize) ComponentError: failed to encode a component from module
$failed to decode world from module

Caused by:
    0: module was not valid
    1: import of `[resource-new]compilerOptions` is not a valid resource function
    at componentNew (file:///Users/cataggar/ms/jco/obj/wasm-tools.js:3714:11)
    at componentNew (file:///Users/cataggar/ms/jco/src/api.js:37:10)
    at async componentize (file:///Users/cataggar/ms/ComponentizeJS/src/componentize.js:381:5)
    at async componentize (file:///Users/cataggar/ms/jco/src/cmd/componentize.js:11:25)
    at async file:///Users/cataggar/ms/jco/src/jco.js:200:9
error: script "componentize" exited with code 1
```

Here is my cowsay.wit where I'm trying to define an empty `resource compiler-options`:
```wit
package local:cowsay;

world cowsay {
  export test: func() -> string;
  export canvas: interface {
    ts-version: func() -> string;
    resource compiler-options {
      // constructor();
    }
  }
}
```

Here is my cowsay.ts where I'm trying to define it:
``` ts
import * as ts from 'typescript';
export function test() {
    return "ok";
}

class CompilerOptions {
    inner;
    constructor() {
        this.inner = 3;
    }
}

function tsVersion() {
    return ts.version;
}

export const canvas = {
    tsVersion: tsVersion,
    compilerOptions(){
        return new CompilerOptions();
    }
    // compilerOptions: (): CompilerOptions => {
    //     return new CompilerOptions();
    // }
};
```

**Comment by guybedford** [comment]
Thanks for confirming, filed as a ComponentizeJS bug.

**Comment by cataggar** [comment]
I was reviewing code this evening. Is `crates/spidermonkey-embedding-splicer/src/bindgen.rs` the right place for this functionality?

**Comment by guybedford** [comment]
It should be, yes.

**Comment by cataggar** [comment]
I wasn't unable to hunt this one down. Would it help if I attached the generated sources?

**Comment by guybedford** [comment]
Fix in https://github.com/bytecodealliance/ComponentizeJS/pull/151.
