### ISSUE TITLE
"module is invalid", "failed to find export of interface" of the imported interface

### ISSUE THREAD

**Issue by cataggar** [bytecodealliance/ComponentizeJS#166]
When I add `import ts:typescript-system/types@0.1.0;`, I get an error that the "module is invalid" and it "failed to find export of interface":

```
$ bunx jco componentize world.js --wit wit -o ts-typescript.wasm -d all
ComponentError: failed to encode a component from module
$failed to decode world from module

Caused by:
    0: module was not valid
    1: failed to find export of interface `ts:typescript-system/types@0.1.0` function `[constructor]system`
    at componentNew (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/obj/wasm-tools.js:3618:11)
    at componentNew (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/src/api.js:37:10)
    at async componentize (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/componentize-js/src/componentize.js:381:5)
    at async componentize (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/src/cmd/componentize.js:11:25)
    at async file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/src/jco.js:200:9
error: script "componentize" exited with code 1
(jco componentize) 
In 'typescript' script 'componentize' failed with exit code 1
```

I'll followup with full steps to reproduce.

**Comment by guybedford** [comment]
The original world being:

```
package ts:typescript@0.1.0;

interface typescript {
    // use ts:typescript-system/types@0.1.0.{system};

    resource program {
      constructor();
      // constructor(sys: system);
      concat-arguments: func() -> string;
    }
}

world root {
  import ts:typescript-system/types@0.1.0;
  // export ts:typescript-system/types@0.1.0;

  // to satisfy jco componentize
  import wasi:io/poll@0.2.2;
  
  // export system;
  export typescript;
}
```
